version: "3.8"
services:
  frontend:
    build:
      context: ./client/ui-react
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Или "80:80", если хотите, чтобы Nginx слушал на порту 80 на хост-машине
    depends_on:
      - backend # Указываем, что frontend зависит от backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://dev_user:dev2134@postgre:5432/feedback_db-dev
      - TELEGRAM_BOT_TOKEN=8127900206:AAH_562gd5k-vASVMuj0XXNfaDcUHzOhpmE
      - WEB_APP_URL=http://frontend
